version: '2.26.0'

services:
  database:
    image: postgres:14.4-alpine3.16
    command: "-c logging_collector=on"
    restart: always
    env_file:
      - config/database.env
    ports:
      - "5433:5432"